// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package authservice

import (
	"context"

	"github.com/geekeryy/api-hub/rpc/user/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AdminLoginReq           = user.AdminLoginReq
	AdminLoginResp          = user.AdminLoginResp
	AdminRegisterReq        = user.AdminRegisterReq
	AdminRegisterResp       = user.AdminRegisterResp
	Empty                   = user.Empty
	GetAdminInfoReq         = user.GetAdminInfoReq
	GetAdminInfoResp        = user.GetAdminInfoResp
	GetJwksReq              = user.GetJwksReq
	GetJwksResp             = user.GetJwksResp
	GetMemberInfoReq        = user.GetMemberInfoReq
	GetMemberInfoResp       = user.GetMemberInfoResp
	MemberActivateEmailReq  = user.MemberActivateEmailReq
	MemberForgetPasswordReq = user.MemberForgetPasswordReq
	MemberLoginReq          = user.MemberLoginReq
	MemberLoginResp         = user.MemberLoginResp
	MemberRefreshTokenReq   = user.MemberRefreshTokenReq
	MemberRefreshTokenResp  = user.MemberRefreshTokenResp
	MemberRegisterReq       = user.MemberRegisterReq
	MemberRegisterResp      = user.MemberRegisterResp

	AuthService interface {
		// 公钥服务
		GetJwks(ctx context.Context, in *GetJwksReq, opts ...grpc.CallOption) (*GetJwksResp, error)
	}

	defaultAuthService struct {
		cli zrpc.Client
	}
)

func NewAuthService(cli zrpc.Client) AuthService {
	return &defaultAuthService{
		cli: cli,
	}
}

// 公钥服务
func (m *defaultAuthService) GetJwks(ctx context.Context, in *GetJwksReq, opts ...grpc.CallOption) (*GetJwksResp, error) {
	client := user.NewAuthServiceClient(m.cli.Conn())
	return client.GetJwks(ctx, in, opts...)
}
