// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: user.proto

package adminservice

import (
	"context"

	"github.com/geekeryy/api-hub/rpc/user/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetAdminInfoReq   = user.GetAdminInfoReq
	GetAdminInfoResp  = user.GetAdminInfoResp
	GetMemberInfoReq  = user.GetMemberInfoReq
	GetMemberInfoResp = user.GetMemberInfoResp

	AdminService interface {
		GetAdminInfo(ctx context.Context, in *GetAdminInfoReq, opts ...grpc.CallOption) (*GetAdminInfoResp, error)
	}

	defaultAdminService struct {
		cli zrpc.Client
	}
)

func NewAdminService(cli zrpc.Client) AdminService {
	return &defaultAdminService{
		cli: cli,
	}
}

func (m *defaultAdminService) GetAdminInfo(ctx context.Context, in *GetAdminInfoReq, opts ...grpc.CallOption) (*GetAdminInfoResp, error) {
	client := user.NewAdminServiceClient(m.cli.Conn())
	return client.GetAdminInfo(ctx, in, opts...)
}
