// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type DeleteKeyReq struct {
	Kid string `json:"kid"`
}

type GetJWKSItem struct {
	Kid string `json:"kid"` // 密钥ID
	Kty string `json:"kty"` // 密钥类型
	Alg string `json:"alg"` // 算法
	Crv string `json:"crv"` // 加密算法曲线
	X   string `json:"x"`   // 公钥
}

type GetJWKSResp struct {
	Data []GetJWKSItem `json:"data"` // 数据
}

type KeyUsageReq struct {
	Kid string `form:"kid"`
}

type KeyUsageResp struct {
	Records []TokenRefreshRecord `json:"records"`
}

type LoginReq struct {
	IdentityType int64  `json:"identity_type,options=8"` // 身份类型 8: otp
	Credential   string `json:"credential"`              // 凭证 密码/验证码/access_token
}

type LoginResp struct {
	Token string `json:"token"` // 令牌
}

type MemberInfoResp struct {
	Nickname string `json:"nickname"` // 昵称
	Avatar   string `json:"avatar"`   // 头像
	Phone    string `json:"phone"`    // 手机号
	Email    string `json:"email"`    // 邮箱
}

type TokenRefreshRecord struct {
	Time  string `json:"time"`
	Count int    `json:"count"`
}
