// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type DeleteKeyReq struct {
	Kid string `json:"kid"`
}

type KeyUsageReq struct {
	Kid string `json:"kid"`
}

type KeyUsageResp struct {
	Records []TokenRefreshRecord `json:"records"`
}

type TokenRefreshRecord struct {
	Time  string `json:"time"`
	Count int    `json:"count"`
}
