// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	rolePermissionsFieldNames          = builder.RawFieldNames(&RolePermissions{})
	rolePermissionsRows                = strings.Join(rolePermissionsFieldNames, ",")
	rolePermissionsRowsExpectAutoSet   = strings.Join(stringx.Remove(rolePermissionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	rolePermissionsRowsWithPlaceHolder = strings.Join(stringx.Remove(rolePermissionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	rolePermissionsModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *RolePermissions) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*RolePermissions, error)
		Update(ctx context.Context, data *RolePermissions) error
		Delete(ctx context.Context, id int64) error
	}

	defaultRolePermissionsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	RolePermissions struct {
		Id           int64     `db:"id"`
		RoleId       int64     `db:"role_id"`
		PermissionId int64     `db:"permission_id"`
		CreatedAt    time.Time `db:"created_at"`
		UpdatedAt    time.Time `db:"updated_at"`
	}
)

func newRolePermissionsModel(conn sqlx.SqlConn) *defaultRolePermissionsModel {
	return &defaultRolePermissionsModel{
		conn:  conn,
		table: "`role_permissions`",
	}
}

func (m *defaultRolePermissionsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultRolePermissionsModel) FindOne(ctx context.Context, id int64) (*RolePermissions, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", rolePermissionsRows, m.table)
	var resp RolePermissions
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRolePermissionsModel) Insert(ctx context.Context, session sqlx.Session, data *RolePermissions) (sql.Result, error) {
	if session == nil {
		session = m.conn
	}
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, rolePermissionsRowsExpectAutoSet)
	ret, err := session.ExecCtx(ctx, query, data.RoleId, data.PermissionId)
	return ret, err
}

func (m *defaultRolePermissionsModel) Update(ctx context.Context, data *RolePermissions) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, rolePermissionsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.RoleId, data.PermissionId, data.Id)
	return err
}

func (m *defaultRolePermissionsModel) tableName() string {
	return m.table
}
