// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package server

import (
	"context"

	"github.com/geekeryy/api-hub/rpc/user/internal/logic/memberservice"
	"github.com/geekeryy/api-hub/rpc/user/internal/svc"
	"github.com/geekeryy/api-hub/rpc/user/user"
)

type MemberServiceServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedMemberServiceServer
}

func NewMemberServiceServer(svcCtx *svc.ServiceContext) *MemberServiceServer {
	return &MemberServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *MemberServiceServer) GetMemberInfo(ctx context.Context, in *user.GetMemberInfoReq) (*user.GetMemberInfoResp, error) {
	l := memberservicelogic.NewGetMemberInfoLogic(ctx, s.svcCtx)
	return l.GetMemberInfo(in)
}
