services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ./grafana-config.ini:/etc/grafana/grafana.ini
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  loki:
    image: grafana/loki:latest
    ports:
      - 3100:3100
    volumes:
      - ./loki-config.yml:/etc/loki/loki.yml
  pyroscope:
    image: grafana/pyroscope
    ports:
      - 4040:4040
  alloy:
    image: grafana/alloy:latest
    ports:
      - 12346:12345
    volumes:
      - ./local-config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock
    env:
      - LOKI_URL=http://localhost:3100
      - PROM_URL=http://localhost:9090
    command: ["run", "--server.http.listen-addr=0.0.0.0:12345", "--storage.path=/var/lib/alloy/data", "/etc/alloy/config.alloy"]
