// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: monitor.proto

package server

import (
	"context"

	"github.com/geekeryy/api-hub/rpc/monitor/internal/logic/monitorservice"
	"github.com/geekeryy/api-hub/rpc/monitor/internal/svc"
	"github.com/geekeryy/api-hub/rpc/monitor/monitor"
)

type MonitorServiceServer struct {
	svcCtx *svc.ServiceContext
	monitor.UnimplementedMonitorServiceServer
}

func NewMonitorServiceServer(svcCtx *svc.ServiceContext) *MonitorServiceServer {
	return &MonitorServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *MonitorServiceServer) ReportUserLoginMetrics(ctx context.Context, in *monitor.ReportUserLoginMetricsReq) (*monitor.Empty, error) {
	l := monitorservicelogic.NewReportUserLoginMetricsLogic(ctx, s.svcCtx)
	return l.ReportUserLoginMetrics(in)
}
