// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: rpc/auth/auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_rpc_auth_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_auth_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_rpc_auth_auth_proto_rawDescGZIP(), []int{0}
}

type MemberLoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityType  int64                  `protobuf:"varint,1,opt,name=identity_type,json=identityType,proto3" json:"identity_type,omitempty"`
	Identifier    string                 `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Credential    string                 `protobuf:"bytes,3,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberLoginReq) Reset() {
	*x = MemberLoginReq{}
	mi := &file_rpc_auth_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberLoginReq) ProtoMessage() {}

func (x *MemberLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_auth_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberLoginReq.ProtoReflect.Descriptor instead.
func (*MemberLoginReq) Descriptor() ([]byte, []int) {
	return file_rpc_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *MemberLoginReq) GetIdentityType() int64 {
	if x != nil {
		return x.IdentityType
	}
	return 0
}

func (x *MemberLoginReq) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *MemberLoginReq) GetCredential() string {
	if x != nil {
		return x.Credential
	}
	return ""
}

type MemberLoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberLoginResp) Reset() {
	*x = MemberLoginResp{}
	mi := &file_rpc_auth_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberLoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberLoginResp) ProtoMessage() {}

func (x *MemberLoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_auth_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberLoginResp.ProtoReflect.Descriptor instead.
func (*MemberLoginResp) Descriptor() ([]byte, []int) {
	return file_rpc_auth_auth_proto_rawDescGZIP(), []int{2}
}

func (x *MemberLoginResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *MemberLoginResp) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type MemberRegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityType  int64                  `protobuf:"varint,1,opt,name=identity_type,json=identityType,proto3" json:"identity_type,omitempty"`
	Identifier    string                 `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Credential    string                 `protobuf:"bytes,3,opt,name=credential,proto3" json:"credential,omitempty"`
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberRegisterReq) Reset() {
	*x = MemberRegisterReq{}
	mi := &file_rpc_auth_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberRegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberRegisterReq) ProtoMessage() {}

func (x *MemberRegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_auth_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberRegisterReq.ProtoReflect.Descriptor instead.
func (*MemberRegisterReq) Descriptor() ([]byte, []int) {
	return file_rpc_auth_auth_proto_rawDescGZIP(), []int{3}
}

func (x *MemberRegisterReq) GetIdentityType() int64 {
	if x != nil {
		return x.IdentityType
	}
	return 0
}

func (x *MemberRegisterReq) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *MemberRegisterReq) GetCredential() string {
	if x != nil {
		return x.Credential
	}
	return ""
}

func (x *MemberRegisterReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type MemberRegisterResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberRegisterResp) Reset() {
	*x = MemberRegisterResp{}
	mi := &file_rpc_auth_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberRegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberRegisterResp) ProtoMessage() {}

func (x *MemberRegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_auth_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberRegisterResp.ProtoReflect.Descriptor instead.
func (*MemberRegisterResp) Descriptor() ([]byte, []int) {
	return file_rpc_auth_auth_proto_rawDescGZIP(), []int{4}
}

func (x *MemberRegisterResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *MemberRegisterResp) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type MemberRefreshTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	MemberUuid    string                 `protobuf:"bytes,2,opt,name=member_uuid,json=memberUuid,proto3" json:"member_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberRefreshTokenReq) Reset() {
	*x = MemberRefreshTokenReq{}
	mi := &file_rpc_auth_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberRefreshTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberRefreshTokenReq) ProtoMessage() {}

func (x *MemberRefreshTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_auth_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberRefreshTokenReq.ProtoReflect.Descriptor instead.
func (*MemberRefreshTokenReq) Descriptor() ([]byte, []int) {
	return file_rpc_auth_auth_proto_rawDescGZIP(), []int{5}
}

func (x *MemberRefreshTokenReq) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *MemberRefreshTokenReq) GetMemberUuid() string {
	if x != nil {
		return x.MemberUuid
	}
	return ""
}

type MemberRefreshTokenResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberRefreshTokenResp) Reset() {
	*x = MemberRefreshTokenResp{}
	mi := &file_rpc_auth_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberRefreshTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberRefreshTokenResp) ProtoMessage() {}

func (x *MemberRefreshTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_auth_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberRefreshTokenResp.ProtoReflect.Descriptor instead.
func (*MemberRefreshTokenResp) Descriptor() ([]byte, []int) {
	return file_rpc_auth_auth_proto_rawDescGZIP(), []int{6}
}

func (x *MemberRefreshTokenResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type MemberActivateEmailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberUuid    string                 `protobuf:"bytes,1,opt,name=member_uuid,json=memberUuid,proto3" json:"member_uuid,omitempty"` // 用户UUID
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`                             // 邮箱
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberActivateEmailReq) Reset() {
	*x = MemberActivateEmailReq{}
	mi := &file_rpc_auth_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberActivateEmailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberActivateEmailReq) ProtoMessage() {}

func (x *MemberActivateEmailReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_auth_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberActivateEmailReq.ProtoReflect.Descriptor instead.
func (*MemberActivateEmailReq) Descriptor() ([]byte, []int) {
	return file_rpc_auth_auth_proto_rawDescGZIP(), []int{7}
}

func (x *MemberActivateEmailReq) GetMemberUuid() string {
	if x != nil {
		return x.MemberUuid
	}
	return ""
}

func (x *MemberActivateEmailReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type MemberForgetPasswordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityType  int64                  `protobuf:"varint,1,opt,name=identity_type,json=identityType,proto3" json:"identity_type,omitempty"`
	Identifier    string                 `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberForgetPasswordReq) Reset() {
	*x = MemberForgetPasswordReq{}
	mi := &file_rpc_auth_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberForgetPasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberForgetPasswordReq) ProtoMessage() {}

func (x *MemberForgetPasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_auth_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberForgetPasswordReq.ProtoReflect.Descriptor instead.
func (*MemberForgetPasswordReq) Descriptor() ([]byte, []int) {
	return file_rpc_auth_auth_proto_rawDescGZIP(), []int{8}
}

func (x *MemberForgetPasswordReq) GetIdentityType() int64 {
	if x != nil {
		return x.IdentityType
	}
	return 0
}

func (x *MemberForgetPasswordReq) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *MemberForgetPasswordReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *MemberForgetPasswordReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AdminLoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityType  int64                  `protobuf:"varint,1,opt,name=identity_type,json=identityType,proto3" json:"identity_type,omitempty"`
	Identifier    string                 `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Credential    string                 `protobuf:"bytes,3,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminLoginReq) Reset() {
	*x = AdminLoginReq{}
	mi := &file_rpc_auth_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminLoginReq) ProtoMessage() {}

func (x *AdminLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_auth_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminLoginReq.ProtoReflect.Descriptor instead.
func (*AdminLoginReq) Descriptor() ([]byte, []int) {
	return file_rpc_auth_auth_proto_rawDescGZIP(), []int{9}
}

func (x *AdminLoginReq) GetIdentityType() int64 {
	if x != nil {
		return x.IdentityType
	}
	return 0
}

func (x *AdminLoginReq) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *AdminLoginReq) GetCredential() string {
	if x != nil {
		return x.Credential
	}
	return ""
}

type AdminLoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminLoginResp) Reset() {
	*x = AdminLoginResp{}
	mi := &file_rpc_auth_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminLoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminLoginResp) ProtoMessage() {}

func (x *AdminLoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_auth_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminLoginResp.ProtoReflect.Descriptor instead.
func (*AdminLoginResp) Descriptor() ([]byte, []int) {
	return file_rpc_auth_auth_proto_rawDescGZIP(), []int{10}
}

func (x *AdminLoginResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AdminLoginResp) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type AdminRegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityType  int64                  `protobuf:"varint,1,opt,name=identity_type,json=identityType,proto3" json:"identity_type,omitempty"`
	Identifier    string                 `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Credential    string                 `protobuf:"bytes,3,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminRegisterReq) Reset() {
	*x = AdminRegisterReq{}
	mi := &file_rpc_auth_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminRegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRegisterReq) ProtoMessage() {}

func (x *AdminRegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_auth_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRegisterReq.ProtoReflect.Descriptor instead.
func (*AdminRegisterReq) Descriptor() ([]byte, []int) {
	return file_rpc_auth_auth_proto_rawDescGZIP(), []int{11}
}

func (x *AdminRegisterReq) GetIdentityType() int64 {
	if x != nil {
		return x.IdentityType
	}
	return 0
}

func (x *AdminRegisterReq) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *AdminRegisterReq) GetCredential() string {
	if x != nil {
		return x.Credential
	}
	return ""
}

type AdminRegisterResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminRegisterResp) Reset() {
	*x = AdminRegisterResp{}
	mi := &file_rpc_auth_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminRegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRegisterResp) ProtoMessage() {}

func (x *AdminRegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_auth_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRegisterResp.ProtoReflect.Descriptor instead.
func (*AdminRegisterResp) Descriptor() ([]byte, []int) {
	return file_rpc_auth_auth_proto_rawDescGZIP(), []int{12}
}

func (x *AdminRegisterResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AdminRegisterResp) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type GetJwksReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJwksReq) Reset() {
	*x = GetJwksReq{}
	mi := &file_rpc_auth_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJwksReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJwksReq) ProtoMessage() {}

func (x *GetJwksReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_auth_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJwksReq.ProtoReflect.Descriptor instead.
func (*GetJwksReq) Descriptor() ([]byte, []int) {
	return file_rpc_auth_auth_proto_rawDescGZIP(), []int{13}
}

func (x *GetJwksReq) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type GetJwksResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJwksResp) Reset() {
	*x = GetJwksResp{}
	mi := &file_rpc_auth_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJwksResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJwksResp) ProtoMessage() {}

func (x *GetJwksResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_auth_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJwksResp.ProtoReflect.Descriptor instead.
func (*GetJwksResp) Descriptor() ([]byte, []int) {
	return file_rpc_auth_auth_proto_rawDescGZIP(), []int{14}
}

func (x *GetJwksResp) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_rpc_auth_auth_proto protoreflect.FileDescriptor

const file_rpc_auth_auth_proto_rawDesc = "" +
	"\n" +
	"\x13rpc/auth/auth.proto\x12\x04auth\"\a\n" +
	"\x05Empty\"u\n" +
	"\x0eMemberLoginReq\x12#\n" +
	"\ridentity_type\x18\x01 \x01(\x03R\fidentityType\x12\x1e\n" +
	"\n" +
	"identifier\x18\x02 \x01(\tR\n" +
	"identifier\x12\x1e\n" +
	"\n" +
	"credential\x18\x03 \x01(\tR\n" +
	"credential\"L\n" +
	"\x0fMemberLoginResp\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"\x8c\x01\n" +
	"\x11MemberRegisterReq\x12#\n" +
	"\ridentity_type\x18\x01 \x01(\x03R\fidentityType\x12\x1e\n" +
	"\n" +
	"identifier\x18\x02 \x01(\tR\n" +
	"identifier\x12\x1e\n" +
	"\n" +
	"credential\x18\x03 \x01(\tR\n" +
	"credential\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\"O\n" +
	"\x12MemberRegisterResp\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"]\n" +
	"\x15MemberRefreshTokenReq\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\x12\x1f\n" +
	"\vmember_uuid\x18\x02 \x01(\tR\n" +
	"memberUuid\".\n" +
	"\x16MemberRefreshTokenResp\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"O\n" +
	"\x16MemberActivateEmailReq\x12\x1f\n" +
	"\vmember_uuid\x18\x01 \x01(\tR\n" +
	"memberUuid\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"\x8e\x01\n" +
	"\x17MemberForgetPasswordReq\x12#\n" +
	"\ridentity_type\x18\x01 \x01(\x03R\fidentityType\x12\x1e\n" +
	"\n" +
	"identifier\x18\x02 \x01(\tR\n" +
	"identifier\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"t\n" +
	"\rAdminLoginReq\x12#\n" +
	"\ridentity_type\x18\x01 \x01(\x03R\fidentityType\x12\x1e\n" +
	"\n" +
	"identifier\x18\x02 \x01(\tR\n" +
	"identifier\x12\x1e\n" +
	"\n" +
	"credential\x18\x03 \x01(\tR\n" +
	"credential\"K\n" +
	"\x0eAdminLoginResp\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"w\n" +
	"\x10AdminRegisterReq\x12#\n" +
	"\ridentity_type\x18\x01 \x01(\x03R\fidentityType\x12\x1e\n" +
	"\n" +
	"identifier\x18\x02 \x01(\tR\n" +
	"identifier\x12\x1e\n" +
	"\n" +
	"credential\x18\x03 \x01(\tR\n" +
	"credential\"N\n" +
	"\x11AdminRegisterResp\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"&\n" +
	"\n" +
	"GetJwksReq\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"!\n" +
	"\vGetJwksResp\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data2\x90\x04\n" +
	"\vAuthService\x12:\n" +
	"\vMemberLogin\x12\x14.auth.MemberLoginReq\x1a\x15.auth.MemberLoginResp\x12C\n" +
	"\x0eMemberRegister\x12\x17.auth.MemberRegisterReq\x1a\x18.auth.MemberRegisterResp\x12O\n" +
	"\x12MemberRefreshToken\x12\x1b.auth.MemberRefreshTokenReq\x1a\x1c.auth.MemberRefreshTokenResp\x12@\n" +
	"\x13MemberActivateEmail\x12\x1c.auth.MemberActivateEmailReq\x1a\v.auth.Empty\x12B\n" +
	"\x14MemberForgetPassword\x12\x1d.auth.MemberForgetPasswordReq\x1a\v.auth.Empty\x127\n" +
	"\n" +
	"AdminLogin\x12\x13.auth.AdminLoginReq\x1a\x14.auth.AdminLoginResp\x12@\n" +
	"\rAdminRegister\x12\x16.auth.AdminRegisterReq\x1a\x17.auth.AdminRegisterResp\x12.\n" +
	"\aGetJwks\x12\x10.auth.GetJwksReq\x1a\x11.auth.GetJwksRespB\bZ\x06./authb\x06proto3"

var (
	file_rpc_auth_auth_proto_rawDescOnce sync.Once
	file_rpc_auth_auth_proto_rawDescData []byte
)

func file_rpc_auth_auth_proto_rawDescGZIP() []byte {
	file_rpc_auth_auth_proto_rawDescOnce.Do(func() {
		file_rpc_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_auth_auth_proto_rawDesc), len(file_rpc_auth_auth_proto_rawDesc)))
	})
	return file_rpc_auth_auth_proto_rawDescData
}

var file_rpc_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_rpc_auth_auth_proto_goTypes = []any{
	(*Empty)(nil),                   // 0: auth.Empty
	(*MemberLoginReq)(nil),          // 1: auth.MemberLoginReq
	(*MemberLoginResp)(nil),         // 2: auth.MemberLoginResp
	(*MemberRegisterReq)(nil),       // 3: auth.MemberRegisterReq
	(*MemberRegisterResp)(nil),      // 4: auth.MemberRegisterResp
	(*MemberRefreshTokenReq)(nil),   // 5: auth.MemberRefreshTokenReq
	(*MemberRefreshTokenResp)(nil),  // 6: auth.MemberRefreshTokenResp
	(*MemberActivateEmailReq)(nil),  // 7: auth.MemberActivateEmailReq
	(*MemberForgetPasswordReq)(nil), // 8: auth.MemberForgetPasswordReq
	(*AdminLoginReq)(nil),           // 9: auth.AdminLoginReq
	(*AdminLoginResp)(nil),          // 10: auth.AdminLoginResp
	(*AdminRegisterReq)(nil),        // 11: auth.AdminRegisterReq
	(*AdminRegisterResp)(nil),       // 12: auth.AdminRegisterResp
	(*GetJwksReq)(nil),              // 13: auth.GetJwksReq
	(*GetJwksResp)(nil),             // 14: auth.GetJwksResp
}
var file_rpc_auth_auth_proto_depIdxs = []int32{
	1,  // 0: auth.AuthService.MemberLogin:input_type -> auth.MemberLoginReq
	3,  // 1: auth.AuthService.MemberRegister:input_type -> auth.MemberRegisterReq
	5,  // 2: auth.AuthService.MemberRefreshToken:input_type -> auth.MemberRefreshTokenReq
	7,  // 3: auth.AuthService.MemberActivateEmail:input_type -> auth.MemberActivateEmailReq
	8,  // 4: auth.AuthService.MemberForgetPassword:input_type -> auth.MemberForgetPasswordReq
	9,  // 5: auth.AuthService.AdminLogin:input_type -> auth.AdminLoginReq
	11, // 6: auth.AuthService.AdminRegister:input_type -> auth.AdminRegisterReq
	13, // 7: auth.AuthService.GetJwks:input_type -> auth.GetJwksReq
	2,  // 8: auth.AuthService.MemberLogin:output_type -> auth.MemberLoginResp
	4,  // 9: auth.AuthService.MemberRegister:output_type -> auth.MemberRegisterResp
	6,  // 10: auth.AuthService.MemberRefreshToken:output_type -> auth.MemberRefreshTokenResp
	0,  // 11: auth.AuthService.MemberActivateEmail:output_type -> auth.Empty
	0,  // 12: auth.AuthService.MemberForgetPassword:output_type -> auth.Empty
	10, // 13: auth.AuthService.AdminLogin:output_type -> auth.AdminLoginResp
	12, // 14: auth.AuthService.AdminRegister:output_type -> auth.AdminRegisterResp
	14, // 15: auth.AuthService.GetJwks:output_type -> auth.GetJwksResp
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_auth_auth_proto_init() }
func file_rpc_auth_auth_proto_init() {
	if File_rpc_auth_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_auth_auth_proto_rawDesc), len(file_rpc_auth_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_auth_auth_proto_goTypes,
		DependencyIndexes: file_rpc_auth_auth_proto_depIdxs,
		MessageInfos:      file_rpc_auth_auth_proto_msgTypes,
	}.Build()
	File_rpc_auth_auth_proto = out.File
	file_rpc_auth_auth_proto_goTypes = nil
	file_rpc_auth_auth_proto_depIdxs = nil
}
