// Code generated by goctl. DO NOT EDIT!

package authmodel

import (
	"context"
	"database/sql"
	"github.com/SpectatorNan/gorm-zero/gormc"

	"github.com/SpectatorNan/gorm-zero/gormc/pagex"
	"gorm.io/gorm"
)

type (
	jwksModel interface {
		Insert(ctx context.Context, tx *gorm.DB, data *Jwks) error
		BatchInsert(ctx context.Context, tx *gorm.DB, news []Jwks) error
		FindOne(ctx context.Context, id int64) (*Jwks, error)
		FindPageList(ctx context.Context, page *pagex.ListReq, orderBy pagex.OrderBy,
			orderKeys map[string]string, whereClause func(db *gorm.DB) *gorm.DB) ([]Jwks, int64, error)
		Update(ctx context.Context, tx *gorm.DB, data *Jwks) error
		BatchUpdate(ctx context.Context, tx *gorm.DB, olds, news []Jwks) error
		BatchDelete(ctx context.Context, tx *gorm.DB, datas []Jwks) error

		Delete(ctx context.Context, tx *gorm.DB, id int64) error
	}

	defaultJwksModel struct {
		conn  *gorm.DB
		table string
	}

	Jwks struct {
		Id         int64          `gorm:"column:id;primary_key"`
		Kid        string         `gorm:"column:kid"`
		PublicKey  string         `gorm:"column:public_key"`
		PrivateKey string         `gorm:"column:private_key"`
		CreatedAt  sql.NullTime   `gorm:"column:created_at"`
		UpdatedAt  sql.NullTime   `gorm:"column:updated_at"`
		DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at;index"`
	}
)

func (Jwks) TableName() string {
	return `"public"."jwks"`
}

func newJwksModel(db *gorm.DB) *defaultJwksModel {
	return &defaultJwksModel{
		conn:  db,
		table: `"public"."jwks"`,
	}
}

func (m *defaultJwksModel) Insert(ctx context.Context, tx *gorm.DB, data *Jwks) error {
	db := m.conn
	if tx != nil {
		db = tx
	}
	err := db.WithContext(ctx).Create(&data).Error
	return err
}
func (m *defaultJwksModel) BatchInsert(ctx context.Context, tx *gorm.DB, news []Jwks) error {
	db := m.conn
	if tx != nil {
		db = tx
	}
	err := db.Create(&news).Error
	return err
}

func (m *defaultJwksModel) FindOne(ctx context.Context, id int64) (*Jwks, error) {
	var resp Jwks
	err := m.conn.WithContext(ctx).Model(&Jwks{}).Where("id = ?", id).Take(&resp).Error
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}
func (m *defaultJwksModel) FindPageList(ctx context.Context, page *pagex.ListReq, orderBy pagex.OrderBy,
	orderKeys map[string]string, whereClause func(db *gorm.DB) *gorm.DB) ([]Jwks, int64, error) {
	conn := m.conn
	formatDB := func() (*gorm.DB, *gorm.DB) {
		db := conn.Model(&Jwks{})
		if whereClause != nil {
			db = whereClause(db)
		}
		return db, nil
	}

	res, total, err := pagex.FindPageListWithCount[Jwks](ctx, page, orderBy, orderKeys, formatDB)
	return res, total, err
}

func (m *defaultJwksModel) Update(ctx context.Context, tx *gorm.DB, data *Jwks) error {
	db := m.conn
	if tx != nil {
		db = tx
	}
	err := db.WithContext(ctx).Save(data).Error
	return err
}
func (m *defaultJwksModel) BatchUpdate(ctx context.Context, tx *gorm.DB, olds, news []Jwks) error {
	db := m.conn
	if tx != nil {
		db = tx
	}
	err := db.WithContext(ctx).Save(&news).Error

	return err
}

func (m *defaultJwksModel) Delete(ctx context.Context, tx *gorm.DB, id int64) error {
	db := m.conn
	if tx != nil {
		db = tx
	}
	err := db.WithContext(ctx).Delete(&Jwks{}, id).Error

	return err
}

func (m *defaultJwksModel) BatchDelete(ctx context.Context, tx *gorm.DB, datas []Jwks) error {
	db := m.conn
	if tx != nil {
		db = tx
	}
	err := db.Delete(&datas).Error
	return err
}
