// Code generated by goctl. DO NOT EDIT!

package authmodel

import (
	"context"
	"database/sql"
	"github.com/SpectatorNan/gorm-zero/gormc"

	"github.com/SpectatorNan/gorm-zero/gormc/pagex"
	"gorm.io/gorm"
)

type (
	memberIdentityModel interface {
		Insert(ctx context.Context, tx *gorm.DB, data *MemberIdentity) error
		BatchInsert(ctx context.Context, tx *gorm.DB, news []MemberIdentity) error
		FindOne(ctx context.Context, id int64) (*MemberIdentity, error)
		FindPageList(ctx context.Context, page *pagex.ListReq, orderBy pagex.OrderBy,
			orderKeys map[string]string, whereClause func(db *gorm.DB) *gorm.DB) ([]MemberIdentity, int64, error)
		Update(ctx context.Context, tx *gorm.DB, data *MemberIdentity) error
		BatchUpdate(ctx context.Context, tx *gorm.DB, olds, news []MemberIdentity) error
		BatchDelete(ctx context.Context, tx *gorm.DB, datas []MemberIdentity) error

		Delete(ctx context.Context, tx *gorm.DB, id int64) error
	}

	defaultMemberIdentityModel struct {
		conn  *gorm.DB
		table string
	}

	MemberIdentity struct {
		Id           int64          `gorm:"column:id;primary_key"`
		MemberId     string         `gorm:"column:member_id"`
		IdentityType int64          `gorm:"column:identity_type"`
		Identifier   string         `gorm:"column:identifier"`
		Credential   string         `gorm:"column:credential"`
		CreatedAt    sql.NullTime   `gorm:"column:created_at"`
		UpdatedAt    sql.NullTime   `gorm:"column:updated_at"`
		DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;index"`
	}
)

func (MemberIdentity) TableName() string {
	return `"public"."member_identity"`
}

func newMemberIdentityModel(db *gorm.DB) *defaultMemberIdentityModel {
	return &defaultMemberIdentityModel{
		conn:  db,
		table: `"public"."member_identity"`,
	}
}

func (m *defaultMemberIdentityModel) Insert(ctx context.Context, tx *gorm.DB, data *MemberIdentity) error {
	db := m.conn
	if tx != nil {
		db = tx
	}
	err := db.WithContext(ctx).Create(&data).Error
	return err
}
func (m *defaultMemberIdentityModel) BatchInsert(ctx context.Context, tx *gorm.DB, news []MemberIdentity) error {
	db := m.conn
	if tx != nil {
		db = tx
	}
	err := db.Create(&news).Error
	return err
}

func (m *defaultMemberIdentityModel) FindOne(ctx context.Context, id int64) (*MemberIdentity, error) {
	var resp MemberIdentity
	err := m.conn.WithContext(ctx).Model(&MemberIdentity{}).Where("id = ?", id).Take(&resp).Error
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}
func (m *defaultMemberIdentityModel) FindPageList(ctx context.Context, page *pagex.ListReq, orderBy pagex.OrderBy,
	orderKeys map[string]string, whereClause func(db *gorm.DB) *gorm.DB) ([]MemberIdentity, int64, error) {
	conn := m.conn
	formatDB := func() (*gorm.DB, *gorm.DB) {
		db := conn.Model(&MemberIdentity{})
		if whereClause != nil {
			db = whereClause(db)
		}
		return db, nil
	}

	res, total, err := pagex.FindPageListWithCount[MemberIdentity](ctx, page, orderBy, orderKeys, formatDB)
	return res, total, err
}

func (m *defaultMemberIdentityModel) Update(ctx context.Context, tx *gorm.DB, data *MemberIdentity) error {
	db := m.conn
	if tx != nil {
		db = tx
	}
	err := db.WithContext(ctx).Save(data).Error
	return err
}
func (m *defaultMemberIdentityModel) BatchUpdate(ctx context.Context, tx *gorm.DB, olds, news []MemberIdentity) error {
	db := m.conn
	if tx != nil {
		db = tx
	}
	err := db.WithContext(ctx).Save(&news).Error

	return err
}

func (m *defaultMemberIdentityModel) Delete(ctx context.Context, tx *gorm.DB, id int64) error {
	db := m.conn
	if tx != nil {
		db = tx
	}
	err := db.WithContext(ctx).Delete(&MemberIdentity{}, id).Error

	return err
}

func (m *defaultMemberIdentityModel) BatchDelete(ctx context.Context, tx *gorm.DB, datas []MemberIdentity) error {
	db := m.conn
	if tx != nil {
		db = tx
	}
	err := db.Delete(&datas).Error
	return err
}
