// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package authmodel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	menusFieldNames          = builder.RawFieldNames(&Menus{})
	menusRows                = strings.Join(menusFieldNames, ",")
	menusRowsExpectAutoSet   = strings.Join(stringx.Remove(menusFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	menusRowsWithPlaceHolder = strings.Join(stringx.Remove(menusFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	menusModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *Menus) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Menus, error)
		Update(ctx context.Context, data *Menus) error
		Delete(ctx context.Context, id int64) error
	}

	defaultMenusModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Menus struct {
		Id          int64     `db:"id"`
		Name        string    `db:"name"`
		Path        string    `db:"path"`
		Icon        string    `db:"icon"`
		Sort        int64     `db:"sort"`
		Pid         int64     `db:"pid"`
		Description string    `db:"description"`
		Status      int64     `db:"status"`
		CreatedAt   time.Time `db:"created_at"`
		UpdatedAt   time.Time `db:"updated_at"`
	}
)

func newMenusModel(conn sqlx.SqlConn) *defaultMenusModel {
	return &defaultMenusModel{
		conn:  conn,
		table: "`menus`",
	}
}

func (m *defaultMenusModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultMenusModel) FindOne(ctx context.Context, id int64) (*Menus, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", menusRows, m.table)
	var resp Menus
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMenusModel) Insert(ctx context.Context, session sqlx.Session, data *Menus) (sql.Result, error) {
	if session == nil {
		session = m.conn
	}
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, menusRowsExpectAutoSet)
	ret, err := session.ExecCtx(ctx, query, data.Name, data.Path, data.Icon, data.Sort, data.Pid, data.Description, data.Status)
	return ret, err
}

func (m *defaultMenusModel) Update(ctx context.Context, data *Menus) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, menusRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Name, data.Path, data.Icon, data.Sort, data.Pid, data.Description, data.Status, data.Id)
	return err
}

func (m *defaultMenusModel) tableName() string {
	return m.table
}
