// Code generated by goctl. DO NOT EDIT!

package authmodel

import (
	"context"
	"database/sql"
	"github.com/SpectatorNan/gorm-zero/gormc"
	"time"

	"github.com/SpectatorNan/gorm-zero/gormc/pagex"
	"gorm.io/gorm"
)

type (
	tokenRefreshRecordModel interface {
		Insert(ctx context.Context, tx *gorm.DB, data *TokenRefreshRecord) error
		BatchInsert(ctx context.Context, tx *gorm.DB, news []TokenRefreshRecord) error
		FindOne(ctx context.Context, id int64) (*TokenRefreshRecord, error)
		FindPageList(ctx context.Context, page *pagex.ListReq, orderBy pagex.OrderBy,
			orderKeys map[string]string, whereClause func(db *gorm.DB) *gorm.DB) ([]TokenRefreshRecord, int64, error)
		FindOneByToken(ctx context.Context, token string) (*TokenRefreshRecord, error)
		Update(ctx context.Context, tx *gorm.DB, data *TokenRefreshRecord) error
		BatchUpdate(ctx context.Context, tx *gorm.DB, olds, news []TokenRefreshRecord) error
		BatchDelete(ctx context.Context, tx *gorm.DB, datas []TokenRefreshRecord) error

		Delete(ctx context.Context, tx *gorm.DB, id int64) error
	}

	defaultTokenRefreshRecordModel struct {
		conn  *gorm.DB
		table string
	}

	TokenRefreshRecord struct {
		Id               int64          `gorm:"column:id;primary_key"`
		RefreshTokenHash string         `gorm:"column:refresh_token_hash"`
		Token            string         `gorm:"column:token"`
		Kid              string         `gorm:"column:kid"`
		Ip               string         `gorm:"column:ip"`
		ExpiredAt        time.Time      `gorm:"column:expired_at"`
		CreatedAt        sql.NullTime   `gorm:"column:created_at"`
		UpdatedAt        sql.NullTime   `gorm:"column:updated_at"`
		DeletedAt        gorm.DeletedAt `gorm:"column:deleted_at;index"`
	}
)

func (TokenRefreshRecord) TableName() string {
	return `"public"."token_refresh_record"`
}

func newTokenRefreshRecordModel(db *gorm.DB) *defaultTokenRefreshRecordModel {
	return &defaultTokenRefreshRecordModel{
		conn:  db,
		table: `"public"."token_refresh_record"`,
	}
}

func (m *defaultTokenRefreshRecordModel) Insert(ctx context.Context, tx *gorm.DB, data *TokenRefreshRecord) error {
	db := m.conn
	if tx != nil {
		db = tx
	}
	err := db.WithContext(ctx).Create(&data).Error
	return err
}
func (m *defaultTokenRefreshRecordModel) BatchInsert(ctx context.Context, tx *gorm.DB, news []TokenRefreshRecord) error {
	db := m.conn
	if tx != nil {
		db = tx
	}
	err := db.Create(&news).Error
	return err
}

func (m *defaultTokenRefreshRecordModel) FindOne(ctx context.Context, id int64) (*TokenRefreshRecord, error) {
	var resp TokenRefreshRecord
	err := m.conn.WithContext(ctx).Model(&TokenRefreshRecord{}).Where("id = ?", id).Take(&resp).Error
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}
func (m *defaultTokenRefreshRecordModel) FindPageList(ctx context.Context, page *pagex.ListReq, orderBy pagex.OrderBy,
	orderKeys map[string]string, whereClause func(db *gorm.DB) *gorm.DB) ([]TokenRefreshRecord, int64, error) {
	conn := m.conn
	formatDB := func() (*gorm.DB, *gorm.DB) {
		db := conn.Model(&TokenRefreshRecord{})
		if whereClause != nil {
			db = whereClause(db)
		}
		return db, nil
	}

	res, total, err := pagex.FindPageListWithCount[TokenRefreshRecord](ctx, page, orderBy, orderKeys, formatDB)
	return res, total, err
}

func (m *defaultTokenRefreshRecordModel) FindOneByToken(ctx context.Context, token string) (*TokenRefreshRecord, error) {
	var resp TokenRefreshRecord
	err := m.conn.WithContext(ctx).Model(&TokenRefreshRecord{}).Where("token = $1", token).Take(&resp).Error
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTokenRefreshRecordModel) Update(ctx context.Context, tx *gorm.DB, data *TokenRefreshRecord) error {
	db := m.conn
	if tx != nil {
		db = tx
	}
	err := db.WithContext(ctx).Save(data).Error
	return err
}
func (m *defaultTokenRefreshRecordModel) BatchUpdate(ctx context.Context, tx *gorm.DB, olds, news []TokenRefreshRecord) error {
	db := m.conn
	if tx != nil {
		db = tx
	}
	err := db.WithContext(ctx).Save(&news).Error

	return err
}

func (m *defaultTokenRefreshRecordModel) Delete(ctx context.Context, tx *gorm.DB, id int64) error {
	db := m.conn
	if tx != nil {
		db = tx
	}
	err := db.WithContext(ctx).Delete(&TokenRefreshRecord{}, id).Error

	return err
}

func (m *defaultTokenRefreshRecordModel) BatchDelete(ctx context.Context, tx *gorm.DB, datas []TokenRefreshRecord) error {
	db := m.conn
	if tx != nil {
		db = tx
	}
	err := db.Delete(&datas).Error
	return err
}
