// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package server

import (
	"context"

	"github.com/geekeryy/api-hub/rpc/user/internal/logic/adminservice"
	"github.com/geekeryy/api-hub/rpc/user/internal/svc"
	"github.com/geekeryy/api-hub/rpc/user/user"
)

type AdminServiceServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedAdminServiceServer
}

func NewAdminServiceServer(svcCtx *svc.ServiceContext) *AdminServiceServer {
	return &AdminServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *AdminServiceServer) GetAdminInfo(ctx context.Context, in *user.GetAdminInfoReq) (*user.GetAdminInfoResp, error) {
	l := adminservicelogic.NewGetAdminInfoLogic(ctx, s.svcCtx)
	return l.GetAdminInfo(in)
}
