// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: monitor.proto

package monitorservice

import (
	"context"

	"github.com/geekeryy/api-hub/rpc/monitor/monitor"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Empty                      = monitor.Empty
	ReportApiAccessMetricsItem = monitor.ReportApiAccessMetricsItem
	ReportApiAccessMetricsReq  = monitor.ReportApiAccessMetricsReq

	MonitorService interface {
		ReportApiAccessMetrics(ctx context.Context, in *ReportApiAccessMetricsReq, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultMonitorService struct {
		cli zrpc.Client
	}
)

func NewMonitorService(cli zrpc.Client) MonitorService {
	return &defaultMonitorService{
		cli: cli,
	}
}

func (m *defaultMonitorService) ReportApiAccessMetrics(ctx context.Context, in *ReportApiAccessMetricsReq, opts ...grpc.CallOption) (*Empty, error) {
	client := monitor.NewMonitorServiceClient(m.cli.Conn())
	return client.ReportApiAccessMetrics(ctx, in, opts...)
}
