// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type DailySentenceReq struct {
	Lang string `form:"lang,omitempty"` // 语言
	Use  string `form:"use,omitempty"`  // 用途 将会传递给Prompt模板，为空时模板不包含用途
}

type DailySentenceResp struct {
	Sentence string `json:"sentence"` // 句子
}

type DeleteKeyReq struct {
	Kid string `json:"kid"`
}

type JWK struct {
	Kty string `json:"kty"`
	Alg string `json:"alg"`
	Kid string `json:"kid"`
	Crv string `json:"crv"`
	X   string `json:"x"`
}

type JWKSResp struct {
	Keys []JWK `json:"keys"`
}

type KeyUsageReq struct {
}

type KeyUsageResp struct {
}

type RotateKeyReq struct {
}
