// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type DailySentenceReq struct {
	Lang string `form:"lang,omitempty"` // 语言
	Use  string `form:"use,omitempty"`  // 用途 将会传递给Prompt模板，为空时模板不包含用途
}

type DailySentenceResp struct {
	Sentence string `json:"sentence"` // 句子
}

type DeleteKeyReq struct {
	PublicKey string `json:"public_key"`
}

type KeyUsageReq struct {
}

type KeyUsageResp struct {
}
