// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: error.proto

package error

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=messageId,proto3" json:"messageId,omitempty"`
	TemplateDate  map[string]string      `protobuf:"bytes,3,rep,name=TemplateDate,proto3" json:"TemplateDate,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Plural        int64                  `protobuf:"varint,4,opt,name=plural,proto3" json:"plural,omitempty"`
	Slacks        []string               `protobuf:"bytes,5,rep,name=slacks,proto3" json:"slacks,omitempty"`
	Status        int64                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	Details       []string               `protobuf:"bytes,7,rep,name=details,proto3" json:"details,omitempty"`
	OriginalError string                 `protobuf:"bytes,8,opt,name=originalError,proto3" json:"originalError,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_error_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Error) GetTemplateDate() map[string]string {
	if x != nil {
		return x.TemplateDate
	}
	return nil
}

func (x *Error) GetPlural() int64 {
	if x != nil {
		return x.Plural
	}
	return 0
}

func (x *Error) GetSlacks() []string {
	if x != nil {
		return x.Slacks
	}
	return nil
}

func (x *Error) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Error) GetDetails() []string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *Error) GetOriginalError() string {
	if x != nil {
		return x.OriginalError
	}
	return ""
}

var File_error_proto protoreflect.FileDescriptor

const file_error_proto_rawDesc = "" +
	"\n" +
	"\verror.proto\x12\x05error\"\xc6\x02\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x1c\n" +
	"\tmessageId\x18\x02 \x01(\tR\tmessageId\x12B\n" +
	"\fTemplateDate\x18\x03 \x03(\v2\x1e.error.Error.TemplateDateEntryR\fTemplateDate\x12\x16\n" +
	"\x06plural\x18\x04 \x01(\x03R\x06plural\x12\x16\n" +
	"\x06slacks\x18\x05 \x03(\tR\x06slacks\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x03R\x06status\x12\x18\n" +
	"\adetails\x18\a \x03(\tR\adetails\x12$\n" +
	"\roriginalError\x18\b \x01(\tR\roriginalError\x1a?\n" +
	"\x11TemplateDateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\tZ\a./errorb\x06proto3"

var (
	file_error_proto_rawDescOnce sync.Once
	file_error_proto_rawDescData []byte
)

func file_error_proto_rawDescGZIP() []byte {
	file_error_proto_rawDescOnce.Do(func() {
		file_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_error_proto_rawDesc), len(file_error_proto_rawDesc)))
	})
	return file_error_proto_rawDescData
}

var file_error_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_error_proto_goTypes = []any{
	(*Error)(nil), // 0: error.Error
	nil,           // 1: error.Error.TemplateDateEntry
}
var file_error_proto_depIdxs = []int32{
	1, // 0: error.Error.TemplateDate:type_name -> error.Error.TemplateDateEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_error_proto_init() }
func file_error_proto_init() {
	if File_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_error_proto_rawDesc), len(file_error_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_error_proto_goTypes,
		DependencyIndexes: file_error_proto_depIdxs,
		MessageInfos:      file_error_proto_msgTypes,
	}.Build()
	File_error_proto = out.File
	file_error_proto_goTypes = nil
	file_error_proto_depIdxs = nil
}
