// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: rpc/user/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMemberInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberUuid    string                 `protobuf:"bytes,1,opt,name=member_uuid,json=memberUuid,proto3" json:"member_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemberInfoReq) Reset() {
	*x = GetMemberInfoReq{}
	mi := &file_rpc_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemberInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberInfoReq) ProtoMessage() {}

func (x *GetMemberInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberInfoReq.ProtoReflect.Descriptor instead.
func (*GetMemberInfoReq) Descriptor() ([]byte, []int) {
	return file_rpc_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *GetMemberInfoReq) GetMemberUuid() string {
	if x != nil {
		return x.MemberUuid
	}
	return ""
}

type GetMemberInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberUuid    string                 `protobuf:"bytes,1,opt,name=MemberUuid,proto3" json:"MemberUuid,omitempty"` // 用户ID
	Nickname      string                 `protobuf:"bytes,2,opt,name=Nickname,proto3" json:"Nickname,omitempty"`     // 昵称
	Avatar        string                 `protobuf:"bytes,3,opt,name=Avatar,proto3" json:"Avatar,omitempty"`         // 头像
	Gender        int64                  `protobuf:"varint,4,opt,name=Gender,proto3" json:"Gender,omitempty"`        // 性别
	Birthday      string                 `protobuf:"bytes,5,opt,name=Birthday,proto3" json:"Birthday,omitempty"`     // 生日
	Phone         string                 `protobuf:"bytes,6,opt,name=Phone,proto3" json:"Phone,omitempty"`           // 手机号
	Email         string                 `protobuf:"bytes,7,opt,name=Email,proto3" json:"Email,omitempty"`           // 邮箱
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemberInfoResp) Reset() {
	*x = GetMemberInfoResp{}
	mi := &file_rpc_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemberInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberInfoResp) ProtoMessage() {}

func (x *GetMemberInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberInfoResp.ProtoReflect.Descriptor instead.
func (*GetMemberInfoResp) Descriptor() ([]byte, []int) {
	return file_rpc_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetMemberInfoResp) GetMemberUuid() string {
	if x != nil {
		return x.MemberUuid
	}
	return ""
}

func (x *GetMemberInfoResp) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GetMemberInfoResp) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GetMemberInfoResp) GetGender() int64 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *GetMemberInfoResp) GetBirthday() string {
	if x != nil {
		return x.Birthday
	}
	return ""
}

func (x *GetMemberInfoResp) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *GetMemberInfoResp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetAdminInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminUuid     string                 `protobuf:"bytes,1,opt,name=admin_uuid,json=adminUuid,proto3" json:"admin_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdminInfoReq) Reset() {
	*x = GetAdminInfoReq{}
	mi := &file_rpc_user_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdminInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminInfoReq) ProtoMessage() {}

func (x *GetAdminInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminInfoReq.ProtoReflect.Descriptor instead.
func (*GetAdminInfoReq) Descriptor() ([]byte, []int) {
	return file_rpc_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetAdminInfoReq) GetAdminUuid() string {
	if x != nil {
		return x.AdminUuid
	}
	return ""
}

type GetAdminInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminUuid     string                 `protobuf:"bytes,1,opt,name=AdminUuid,proto3" json:"AdminUuid,omitempty"` // 管理员ID
	Username      string                 `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`   // 用户名
	Email         string                 `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`         // 邮箱
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdminInfoResp) Reset() {
	*x = GetAdminInfoResp{}
	mi := &file_rpc_user_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdminInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminInfoResp) ProtoMessage() {}

func (x *GetAdminInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminInfoResp.ProtoReflect.Descriptor instead.
func (*GetAdminInfoResp) Descriptor() ([]byte, []int) {
	return file_rpc_user_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetAdminInfoResp) GetAdminUuid() string {
	if x != nil {
		return x.AdminUuid
	}
	return ""
}

func (x *GetAdminInfoResp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetAdminInfoResp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_rpc_user_user_proto protoreflect.FileDescriptor

const file_rpc_user_user_proto_rawDesc = "" +
	"\n" +
	"\x13rpc/user/user.proto\x12\x04user\"3\n" +
	"\x10GetMemberInfoReq\x12\x1f\n" +
	"\vmember_uuid\x18\x01 \x01(\tR\n" +
	"memberUuid\"\xc7\x01\n" +
	"\x11GetMemberInfoResp\x12\x1e\n" +
	"\n" +
	"MemberUuid\x18\x01 \x01(\tR\n" +
	"MemberUuid\x12\x1a\n" +
	"\bNickname\x18\x02 \x01(\tR\bNickname\x12\x16\n" +
	"\x06Avatar\x18\x03 \x01(\tR\x06Avatar\x12\x16\n" +
	"\x06Gender\x18\x04 \x01(\x03R\x06Gender\x12\x1a\n" +
	"\bBirthday\x18\x05 \x01(\tR\bBirthday\x12\x14\n" +
	"\x05Phone\x18\x06 \x01(\tR\x05Phone\x12\x14\n" +
	"\x05Email\x18\a \x01(\tR\x05Email\"0\n" +
	"\x0fGetAdminInfoReq\x12\x1d\n" +
	"\n" +
	"admin_uuid\x18\x01 \x01(\tR\tadminUuid\"b\n" +
	"\x10GetAdminInfoResp\x12\x1c\n" +
	"\tAdminUuid\x18\x01 \x01(\tR\tAdminUuid\x12\x1a\n" +
	"\bUsername\x18\x02 \x01(\tR\bUsername\x12\x14\n" +
	"\x05Email\x18\x03 \x01(\tR\x05Email2M\n" +
	"\fAdminService\x12=\n" +
	"\fGetAdminInfo\x12\x15.user.GetAdminInfoReq\x1a\x16.user.GetAdminInfoResp2Q\n" +
	"\rMemberService\x12@\n" +
	"\rGetMemberInfo\x12\x16.user.GetMemberInfoReq\x1a\x17.user.GetMemberInfoRespB\bZ\x06./userb\x06proto3"

var (
	file_rpc_user_user_proto_rawDescOnce sync.Once
	file_rpc_user_user_proto_rawDescData []byte
)

func file_rpc_user_user_proto_rawDescGZIP() []byte {
	file_rpc_user_user_proto_rawDescOnce.Do(func() {
		file_rpc_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_user_user_proto_rawDesc), len(file_rpc_user_user_proto_rawDesc)))
	})
	return file_rpc_user_user_proto_rawDescData
}

var file_rpc_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpc_user_user_proto_goTypes = []any{
	(*GetMemberInfoReq)(nil),  // 0: user.GetMemberInfoReq
	(*GetMemberInfoResp)(nil), // 1: user.GetMemberInfoResp
	(*GetAdminInfoReq)(nil),   // 2: user.GetAdminInfoReq
	(*GetAdminInfoResp)(nil),  // 3: user.GetAdminInfoResp
}
var file_rpc_user_user_proto_depIdxs = []int32{
	2, // 0: user.AdminService.GetAdminInfo:input_type -> user.GetAdminInfoReq
	0, // 1: user.MemberService.GetMemberInfo:input_type -> user.GetMemberInfoReq
	3, // 2: user.AdminService.GetAdminInfo:output_type -> user.GetAdminInfoResp
	1, // 3: user.MemberService.GetMemberInfo:output_type -> user.GetMemberInfoResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_user_user_proto_init() }
func file_rpc_user_user_proto_init() {
	if File_rpc_user_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_user_user_proto_rawDesc), len(file_rpc_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_rpc_user_user_proto_goTypes,
		DependencyIndexes: file_rpc_user_user_proto_depIdxs,
		MessageInfos:      file_rpc_user_user_proto_msgTypes,
	}.Build()
	File_rpc_user_user_proto = out.File
	file_rpc_user_user_proto_goTypes = nil
	file_rpc_user_user_proto_depIdxs = nil
}
