// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package server

import (
	"context"

	"github.com/geekeryy/api-hub/rpc/user/internal/logic/authservice"
	"github.com/geekeryy/api-hub/rpc/user/internal/svc"
	"github.com/geekeryy/api-hub/rpc/user/user"
)

type AuthServiceServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedAuthServiceServer
}

func NewAuthServiceServer(svcCtx *svc.ServiceContext) *AuthServiceServer {
	return &AuthServiceServer{
		svcCtx: svcCtx,
	}
}

// 公钥服务
func (s *AuthServiceServer) GetJwks(ctx context.Context, in *user.GetJwksReq) (*user.GetJwksResp, error) {
	l := authservicelogic.NewGetJwksLogic(ctx, s.svcCtx)
	return l.GetJwks(in)
}
