name: Golang CI Lint

on:
  push:
    branches: [ "dev","feature/**","fix/**" ]
  pull_request:

jobs:
  ci:
    name: Golang CI Lint
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: "**/*.sum"

      - name: Golang CI Lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0
